// Code generated by protoc-gen-go. DO NOT EDIT.
// source: levels.proto

package pbLevels

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllLevelRequest struct {
	TeamID               string   `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllLevelRequest) Reset()         { *m = AllLevelRequest{} }
func (m *AllLevelRequest) String() string { return proto.CompactTextString(m) }
func (*AllLevelRequest) ProtoMessage()    {}
func (*AllLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{0}
}

func (m *AllLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllLevelRequest.Unmarshal(m, b)
}
func (m *AllLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllLevelRequest.Marshal(b, m, deterministic)
}
func (m *AllLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllLevelRequest.Merge(m, src)
}
func (m *AllLevelRequest) XXX_Size() int {
	return xxx_messageInfo_AllLevelRequest.Size(m)
}
func (m *AllLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllLevelRequest proto.InternalMessageInfo

func (m *AllLevelRequest) GetTeamID() string {
	if m != nil {
		return m.TeamID
	}
	return ""
}

type AllLevelResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllLevelResponse) Reset()         { *m = AllLevelResponse{} }
func (m *AllLevelResponse) String() string { return proto.CompactTextString(m) }
func (*AllLevelResponse) ProtoMessage()    {}
func (*AllLevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{1}
}

func (m *AllLevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllLevelResponse.Unmarshal(m, b)
}
func (m *AllLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllLevelResponse.Marshal(b, m, deterministic)
}
func (m *AllLevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllLevelResponse.Merge(m, src)
}
func (m *AllLevelResponse) XXX_Size() int {
	return xxx_messageInfo_AllLevelResponse.Size(m)
}
func (m *AllLevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllLevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllLevelResponse proto.InternalMessageInfo

func (m *AllLevelResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AnswerRequest struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	TeamID               string   `protobuf:"bytes,3,opt,name=teamID,proto3" json:"teamID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerRequest) Reset()         { *m = AnswerRequest{} }
func (m *AnswerRequest) String() string { return proto.CompactTextString(m) }
func (*AnswerRequest) ProtoMessage()    {}
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{2}
}

func (m *AnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerRequest.Unmarshal(m, b)
}
func (m *AnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerRequest.Marshal(b, m, deterministic)
}
func (m *AnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerRequest.Merge(m, src)
}
func (m *AnswerRequest) XXX_Size() int {
	return xxx_messageInfo_AnswerRequest.Size(m)
}
func (m *AnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerRequest proto.InternalMessageInfo

func (m *AnswerRequest) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *AnswerRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *AnswerRequest) GetTeamID() string {
	if m != nil {
		return m.TeamID
	}
	return ""
}

type AnswerResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerResponse) Reset()         { *m = AnswerResponse{} }
func (m *AnswerResponse) String() string { return proto.CompactTextString(m) }
func (*AnswerResponse) ProtoMessage()    {}
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{3}
}

func (m *AnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerResponse.Unmarshal(m, b)
}
func (m *AnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerResponse.Marshal(b, m, deterministic)
}
func (m *AnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerResponse.Merge(m, src)
}
func (m *AnswerResponse) XXX_Size() int {
	return xxx_messageInfo_AnswerResponse.Size(m)
}
func (m *AnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerResponse proto.InternalMessageInfo

func (m *AnswerResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type LevelResponse struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Urlalias             string   `protobuf:"bytes,3,opt,name=urlalias,proto3" json:"urlalias,omitempty"`
	Html                 string   `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	Js                   string   `protobuf:"bytes,5,opt,name=js,proto3" json:"js,omitempty"`
	Final                bool     `protobuf:"varint,6,opt,name=final,proto3" json:"final,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelResponse) Reset()         { *m = LevelResponse{} }
func (m *LevelResponse) String() string { return proto.CompactTextString(m) }
func (*LevelResponse) ProtoMessage()    {}
func (*LevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{4}
}

func (m *LevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelResponse.Unmarshal(m, b)
}
func (m *LevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelResponse.Marshal(b, m, deterministic)
}
func (m *LevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelResponse.Merge(m, src)
}
func (m *LevelResponse) XXX_Size() int {
	return xxx_messageInfo_LevelResponse.Size(m)
}
func (m *LevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LevelResponse proto.InternalMessageInfo

func (m *LevelResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *LevelResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LevelResponse) GetUrlalias() string {
	if m != nil {
		return m.Urlalias
	}
	return ""
}

func (m *LevelResponse) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *LevelResponse) GetJs() string {
	if m != nil {
		return m.Js
	}
	return ""
}

func (m *LevelResponse) GetFinal() bool {
	if m != nil {
		return m.Final
	}
	return false
}

type LevelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamID               string   `protobuf:"bytes,2,opt,name=teamID,proto3" json:"teamID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelRequest) Reset()         { *m = LevelRequest{} }
func (m *LevelRequest) String() string { return proto.CompactTextString(m) }
func (*LevelRequest) ProtoMessage()    {}
func (*LevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd466c55a41d32c, []int{5}
}

func (m *LevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelRequest.Unmarshal(m, b)
}
func (m *LevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelRequest.Marshal(b, m, deterministic)
}
func (m *LevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelRequest.Merge(m, src)
}
func (m *LevelRequest) XXX_Size() int {
	return xxx_messageInfo_LevelRequest.Size(m)
}
func (m *LevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LevelRequest proto.InternalMessageInfo

func (m *LevelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LevelRequest) GetTeamID() string {
	if m != nil {
		return m.TeamID
	}
	return ""
}

func init() {
	proto.RegisterType((*AllLevelRequest)(nil), "levels.AllLevelRequest")
	proto.RegisterType((*AllLevelResponse)(nil), "levels.AllLevelResponse")
	proto.RegisterType((*AnswerRequest)(nil), "levels.AnswerRequest")
	proto.RegisterType((*AnswerResponse)(nil), "levels.AnswerResponse")
	proto.RegisterType((*LevelResponse)(nil), "levels.LevelResponse")
	proto.RegisterType((*LevelRequest)(nil), "levels.LevelRequest")
}

func init() { proto.RegisterFile("levels.proto", fileDescriptor_2dd466c55a41d32c) }

var fileDescriptor_2dd466c55a41d32c = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0x92, 0xaf, 0x89, 0xd2, 0xed, 0x0f, 0xc8, 0x2a, 0xc5, 0xca, 0x09, 0xf9, 0x80, 0xca,
	0xa5, 0x07, 0x90, 0x90, 0xb8, 0x20, 0xb5, 0x20, 0x55, 0x48, 0x9c, 0x7c, 0x41, 0xe2, 0xe6, 0xd2,
	0x45, 0x4d, 0x71, 0x92, 0x12, 0xbb, 0xe5, 0x39, 0x78, 0x29, 0x9e, 0x0b, 0xc5, 0x4e, 0xd2, 0xb8,
	0xdc, 0x76, 0x26, 0xb3, 0xb3, 0xb3, 0x59, 0x43, 0x5f, 0xe2, 0x1e, 0xa5, 0x9a, 0x6e, 0x8b, 0x5c,
	0xe7, 0x24, 0xb4, 0x88, 0x5d, 0xc1, 0xc9, 0x4c, 0xca, 0xe7, 0x12, 0x70, 0xfc, 0xdc, 0xa1, 0xd2,
	0x64, 0x0c, 0xa1, 0x46, 0x91, 0x3e, 0x3d, 0x52, 0xef, 0xc2, 0x9b, 0x74, 0x79, 0x85, 0xd8, 0x04,
	0x4e, 0x0f, 0x52, 0xb5, 0xcd, 0x33, 0x85, 0x64, 0x04, 0x81, 0xce, 0xb5, 0x90, 0x46, 0x1a, 0x70,
	0x0b, 0xd8, 0x0b, 0x0c, 0x66, 0x99, 0xfa, 0xc2, 0xa2, 0x65, 0x29, 0x0c, 0x51, 0x5b, 0x5a, 0x54,
	0xf2, 0xd9, 0x2e, 0x5d, 0x62, 0x41, 0x7d, 0xd3, 0x5f, 0xa1, 0x56, 0x84, 0xff, 0x4e, 0x84, 0x4b,
	0x18, 0xd6, 0xc6, 0x87, 0x00, 0x7b, 0x21, 0x93, 0x95, 0x31, 0x8e, 0xb8, 0x05, 0xec, 0xdb, 0x83,
	0x81, 0x1b, 0xf4, 0x30, 0xc9, 0x73, 0x26, 0x11, 0xe8, 0x64, 0x22, 0x45, 0x33, 0xbf, 0xcb, 0x4d,
	0x4d, 0x62, 0x88, 0x76, 0x85, 0x14, 0x32, 0x11, 0xaa, 0x9a, 0xdf, 0xe0, 0x52, 0xbf, 0xd6, 0xa9,
	0xa4, 0x1d, 0xab, 0x2f, 0x6b, 0x32, 0x04, 0x7f, 0xa3, 0x68, 0x60, 0x18, 0x7f, 0xa3, 0xca, 0x4c,
	0xef, 0x49, 0x26, 0x24, 0x0d, 0x6d, 0x26, 0x03, 0xd8, 0x2d, 0xf4, 0x9d, 0xdf, 0x3c, 0x04, 0xbf,
	0x8a, 0x1d, 0x70, 0x3f, 0x59, 0xb5, 0x76, 0xf6, 0xdb, 0x3b, 0x5f, 0xff, 0x78, 0x10, 0x98, 0x46,
	0x72, 0x07, 0xd1, 0x02, 0xb5, 0xad, 0x47, 0xd3, 0xea, 0x9c, 0x6d, 0xcf, 0xf8, 0xec, 0x88, 0xb5,
	0xcb, 0xb3, 0x7f, 0xe4, 0x1e, 0x7a, 0x0f, 0x6b, 0x7c, 0xfb, 0xb0, 0x7f, 0x8f, 0x34, 0x3a, 0xe7,
	0x4c, 0xf1, 0xf8, 0x98, 0x6e, 0xfa, 0xe7, 0xd0, 0x5b, 0xa0, 0xae, 0xcf, 0x4f, 0xce, 0x1b, 0xa1,
	0xfb, 0x76, 0x62, 0xfa, 0xf7, 0x43, 0xed, 0x31, 0x87, 0xd7, 0x68, 0xbb, 0x34, 0xa4, 0x5a, 0x86,
	0xe6, 0x15, 0xde, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xdd, 0xf5, 0x0a, 0x95, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LevelClient is the client API for Level service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LevelClient interface {
	GetLevel(ctx context.Context, in *LevelRequest, opts ...grpc.CallOption) (*LevelResponse, error)
	CheckAnswer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
	GetAllLevel(ctx context.Context, in *AllLevelRequest, opts ...grpc.CallOption) (*AllLevelResponse, error)
}

type levelClient struct {
	cc *grpc.ClientConn
}

func NewLevelClient(cc *grpc.ClientConn) LevelClient {
	return &levelClient{cc}
}

func (c *levelClient) GetLevel(ctx context.Context, in *LevelRequest, opts ...grpc.CallOption) (*LevelResponse, error) {
	out := new(LevelResponse)
	err := c.cc.Invoke(ctx, "/levels.Level/GetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelClient) CheckAnswer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, "/levels.Level/CheckAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelClient) GetAllLevel(ctx context.Context, in *AllLevelRequest, opts ...grpc.CallOption) (*AllLevelResponse, error) {
	out := new(AllLevelResponse)
	err := c.cc.Invoke(ctx, "/levels.Level/GetAllLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LevelServer is the server API for Level service.
type LevelServer interface {
	GetLevel(context.Context, *LevelRequest) (*LevelResponse, error)
	CheckAnswer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	GetAllLevel(context.Context, *AllLevelRequest) (*AllLevelResponse, error)
}

// UnimplementedLevelServer can be embedded to have forward compatible implementations.
type UnimplementedLevelServer struct {
}

func (*UnimplementedLevelServer) GetLevel(ctx context.Context, req *LevelRequest) (*LevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevel not implemented")
}
func (*UnimplementedLevelServer) CheckAnswer(ctx context.Context, req *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAnswer not implemented")
}
func (*UnimplementedLevelServer) GetAllLevel(ctx context.Context, req *AllLevelRequest) (*AllLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLevel not implemented")
}

func RegisterLevelServer(s *grpc.Server, srv LevelServer) {
	s.RegisterService(&_Level_serviceDesc, srv)
}

func _Level_GetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServer).GetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/levels.Level/GetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServer).GetLevel(ctx, req.(*LevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Level_CheckAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServer).CheckAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/levels.Level/CheckAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServer).CheckAnswer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Level_GetAllLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServer).GetAllLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/levels.Level/GetAllLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServer).GetAllLevel(ctx, req.(*AllLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Level_serviceDesc = grpc.ServiceDesc{
	ServiceName: "levels.Level",
	HandlerType: (*LevelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLevel",
			Handler:    _Level_GetLevel_Handler,
		},
		{
			MethodName: "CheckAnswer",
			Handler:    _Level_CheckAnswer_Handler,
		},
		{
			MethodName: "GetAllLevel",
			Handler:    _Level_GetAllLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "levels.proto",
}
